# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puma'
gem 'rack-test'
gem 'sinatra'
gem 'registry-client', git: 'https://github.com/hojulian/service-api-example.git', branch: 'gemv2', glob: 'registry-client/*.gemspec'
